### ISSUE TITLE
코드 저장 임시 파일 커밋되기전 함수 업로드 - 혜은 파트 

### ISSUE THREAD

**Issue by yeonhyeeun** [mayeonn/Group10#9]
//8번 함수 
int selectDataNum(Song *s, int count) {
    int no; 
    listsong(s, count);
    printf("번호는? (취소:0) ");
    scanf("%d", &no);
    return no; }

**Comment by mayeonn** [comment]
wiki에 올릴 내용은 파일에 md 파일로 올려주시면 제가 복붙 하겠습니다

**Comment by yeonhyeeun** [comment]
넵!! 감사합니다!
